# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui/main_gui2.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 510)
        MainWindow.setMinimumSize(QtCore.QSize(600, 510))
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setEnabled(True)
        self.splitter.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.splitter.setFrameShadow(QtWidgets.QFrame.Plain)
        self.splitter.setMidLineWidth(1)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setHandleWidth(0)
        self.splitter.setObjectName("splitter")
        self.fRaidList = QtWidgets.QWidget(self.splitter)
        self.fRaidList.setObjectName("fRaidList")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.fRaidList)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.treeWidget = QtWidgets.QTreeWidget(self.fRaidList)
        self.treeWidget.setMinimumSize(QtCore.QSize(400, 0))
        self.treeWidget.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.treeWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.header().setCascadingSectionResizes(True)
        self.horizontalLayout.addWidget(self.treeWidget)
        self.fOptions = QtWidgets.QFrame(self.splitter)
        self.fOptions.setMinimumSize(QtCore.QSize(150, 0))
        self.fOptions.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.fOptions.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fOptions.setObjectName("fOptions")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.fOptions)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pbUploadSelection = QtWidgets.QPushButton(self.fOptions)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbUploadSelection.sizePolicy().hasHeightForWidth())
        self.pbUploadSelection.setSizePolicy(sizePolicy)
        self.pbUploadSelection.setObjectName("pbUploadSelection")
        self.verticalLayout.addWidget(self.pbUploadSelection)
        self.cbChannelSelect = QtWidgets.QComboBox(self.fOptions)
        self.cbChannelSelect.setObjectName("cbChannelSelect")
        self.verticalLayout.addWidget(self.cbChannelSelect)
        self.pbOpenLogs = QtWidgets.QPushButton(self.fOptions)
        self.pbOpenLogs.setEnabled(False)
        self.pbOpenLogs.setObjectName("pbOpenLogs")
        self.verticalLayout.addWidget(self.pbOpenLogs)
        self.pbCopyLatest = QtWidgets.QPushButton(self.fOptions)
        self.pbCopyLatest.setObjectName("pbCopyLatest")
        self.verticalLayout.addWidget(self.pbCopyLatest)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.pbRefresh = QtWidgets.QPushButton(self.fOptions)
        self.pbRefresh.setObjectName("pbRefresh")
        self.verticalLayout.addWidget(self.pbRefresh)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.pbTest = QtWidgets.QPushButton(self.fOptions)
        self.pbTest.setObjectName("pbTest")
        self.verticalLayout.addWidget(self.pbTest)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.pbChooseFolder = QtWidgets.QPushButton(self.fOptions)
        self.pbChooseFolder.setObjectName("pbChooseFolder")
        self.verticalLayout.addWidget(self.pbChooseFolder)
        self.lCutoffDate = QtWidgets.QLabel(self.fOptions)
        self.lCutoffDate.setObjectName("lCutoffDate")
        self.verticalLayout.addWidget(self.lCutoffDate)
        self.dteCutoffDate = QtWidgets.QDateTimeEdit(self.fOptions)
        self.dteCutoffDate.setEnabled(False)
        self.dteCutoffDate.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.dteCutoffDate.setCalendarPopup(True)
        self.dteCutoffDate.setObjectName("dteCutoffDate")
        self.verticalLayout.addWidget(self.dteCutoffDate)
        self.verticalLayout_2.addWidget(self.splitter)
        self.fFooter = QtWidgets.QFrame(self.centralwidget)
        self.fFooter.setMaximumSize(QtCore.QSize(16777215, 30))
        self.fFooter.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fFooter.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fFooter.setObjectName("fFooter")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.fFooter)
        self.horizontalLayout_2.setContentsMargins(-1, 3, -1, 3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lUploadStatus = QtWidgets.QLabel(self.fFooter)
        self.lUploadStatus.setObjectName("lUploadStatus")
        self.horizontalLayout_2.addWidget(self.lUploadStatus)
        self.progressBarUpload = customProgressBar(self.fFooter)
        self.progressBarUpload.setMinimumSize(QtCore.QSize(0, 0))
        self.progressBarUpload.setMaximum(1)
        self.progressBarUpload.setProperty("value", 0)
        self.progressBarUpload.setObjectName("progressBarUpload")
        self.horizontalLayout_2.addWidget(self.progressBarUpload)
        self.verticalLayout_2.addWidget(self.fFooter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setEnabled(False)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 21))
        self.menubar.setObjectName("menubar")
        self.menuQuit = QtWidgets.QMenu(self.menubar)
        self.menuQuit.setObjectName("menuQuit")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuQuit.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "GW2 Log Uploader"))
        self.treeWidget.headerItem().setText(0, _translate("MainWindow", "Raids"))
        self.treeWidget.headerItem().setText(1, _translate("MainWindow", "most recent run"))
        self.pbUploadSelection.setText(_translate("MainWindow", "post selected logs \n"
" to discord"))
        self.pbOpenLogs.setText(_translate("MainWindow", "open logs in browser"))
        self.pbCopyLatest.setText(_translate("MainWindow", "copy latest upload \n"
" to clipboard"))
        self.pbRefresh.setText(_translate("MainWindow", "refresh data"))
        self.pbTest.setText(_translate("MainWindow", "big red button"))
        self.pbChooseFolder.setText(_translate("MainWindow", "select log folder"))
        self.lCutoffDate.setText(_translate("MainWindow", "Choose a cut-off date"))
        self.dteCutoffDate.setToolTip(_translate("MainWindow", "Any logs that were saved before this date will not be considered when looking for logs to upload!"))
        self.dteCutoffDate.setDisplayFormat(_translate("MainWindow", "dd/MM/yyyy HH:mm"))
        self.lUploadStatus.setText(_translate("MainWindow", "upload status"))
        self.progressBarUpload.setFormat(_translate("MainWindow", "%v of %m files uploaded"))
        self.menuQuit.setTitle(_translate("MainWindow", "Quit"))

from customProgressBar import customProgressBar
