from discord_hooks import Webhook
import datetime

class cRaidclear():
    def __init__(self, date=datetime.datetime.now().strftime("%d/%m/%Y")):
        self.bosses = {}
        self.date = date
        self.placeholder_icon = "<:FeelsDeadMan:446396105077424138>"
        self.iconmap = {"Vale Guardian": "<:vale_guardian:449838205701718016>",
                        "Gorseval": "<:gorseval:449838206179868672>",
                        "Sabetha": "<:sabetha:449838205118971909>",
                        "Slothasor": "<:sloth:449838206045913098>",
                        "Matthias": "<:matthias:449838206054170645>",
                        "Keep Construct": "<:keep_construct:449838205731340290>",
                        "Xera": "<:xera:449838206100176896>",
                        "Cairn": "<:cairn:449838199523639307>",
                        "Mursaat Overseer": "<:mursaat_overseer:449838206310023168>",
                        "Samarog":"<:samarog:449838206205296650>",
                        "Deimos": "<:deimos:449838200295391232> ",
                        "Soulless Horror": "<:soulless_horror:449838201943621632>",
                        "Dhuum":"<:dhuum:449838200999903232>"}

        self.iconmap2 = {"Vale Guardian": "<:vale_guardian:449831911993507850>",
                        "Gorseval": "<:gorseval:449831912190771210>",
                        "Sabetha": "<:sabetha:449831912006221824>",
                        "Slothasor": "<:sloth:449831912064679946>",
                        "Matthias": "<:matthias:449831912177926144>",
                        "Keep Construct": "<:keep_construct:449831911674740737>",
                        "Xera": "<:xera:449831911754432513>",
                        "Cairn": "<:cairn:449831905186283551>",
                        "Mursaat Overseer": "<:mursaat_overseer:449831912123400204>",
                        "Samarog":"<:samarog:449831912526315520>",
                        "Deimos": "<:deimos:449831906188591114>",
                        "Soulless Horror": "<:soulless_horror:449831907509796878>",
                        "Dhuum":"<:dhuum:449831907530899476>"}

        #{"hook_url1":}

        self.hook_url1 = "https://discordapp.com/api/webhooks/449753822038851606/pAgpZpm1WxGPc_t-UO94pEbz9AUmpYN9BjE7RVb0GZd3HhQZTS1JmNMXn_8VthAkaWBX" #this is the testserver
        self.hook_url2 = "https://discordapp.com/api/webhooks/449702660568907777/QAA68ltV3vXKxWr5_FgSJln3K5QAciPn9dwEiv_ZTOD8IjhDQtHVdGhTOLLpdhgCT8-p" # this is the dps report channel
        self.hook_url = self.hook_url2
        self.embed = Webhook(self.hook_url, color=0x483768)
        self.embed.set_desc("__***[Meta] Raid Run on "+self.date+"***__")
        self.embed.set_thumbnail("https://wiki.guildwars2.com/images/9/9d/Epidemic.png")
        self.embed.set_footer(text="Participants: Some people", ts=False)

    def set_bosses(self, bosses):
        """bosses is a dict that containts the bosses + links """
        self.bosses = bosses

    def add_bossfields(self):
        for key in self.bosses.keys():
            self.embed.add_field(name=self.iconmap.get(key, self.placeholder_icon)+key, value="[dps.report]("+self.bosses[key]+" \""+self.bosses[key]+"\")")

    def post_to_discord(self):
        #self.embed.set_desc("I am a descriptive description describing in a descriptive way.")
        self.embed.set_author(name="Chrononono")
        self.embed.post()

    def test_message(self):
        test_message = self.embed
        test_message.add_field(name="This is a test!", value="Nothing to see here")
        test_message.set_desc("A very inconspicuous message")
        test_message.set_author(name="Rogue AI")
        test_message.set_footer(text="", ts=False)
        test_message.post()


# this is a thing that needs to bbe generated by the log uploader
#bosses = {"Vale Guardian": "https://dps.report/p0eu-20180521-220333_vg",
#           "Gorseval": "https://dps.report/Mios-20180521-220828_gorse",
#           "Sabetha": "https://dps.report/kZ1Y-20180525-192248_sab",
#           "Slothasor":"https://dps.report/RNrA-20180521-211924_sloth",
#           "Matthias": "https://dps.report/cDz1-20180525-193659_matt",
#           "Keep Construct": "https://dps.report/mfCd-20180521-205618_kc",
#           "Xera": "https://dps.report/RrK4-20180521-210827_xera",
#           "Cairn": "https://dps.report/8igT-20180521-190334_cairn",
#           "Mursaat Overseer": "https://dps.report/WARN-20180521-190741_mo",
#           "Samarog": "https://dps.report/oolK-20180521-192008_sam",
#           "Deimos": "https://dps.report/ls0E-20180521-194534_dei",
#           "Soulless Horror": "https://dps.report/E2PQ-20180521-195716_sh",
#           "Dhuum": "https://dps.report/gnqM-20180525-191100_dhuum"
#           }

#temp = cRaidclear()
#for key in bosses.keys():
#    embed.add_field(name=temp.iconmap.get(key, "whoops")+key, value="[dps.report]("+bosses[key]+" \""+bosses[key]+"\")")

#embed.set_thumbnail("https://wiki.guildwars2.com/images/9/9d/Epidemic.png")
#embed.set_footer(text="Participants: Some people", ts=False)

#embed.post()
