from discord_hooks import Webhook
import datetime

class cRaidclear():
    def __init__(self, hook_url, date=datetime.datetime.now().strftime("%d/%m/%Y")):
        self.bosses = {}
        self.date = date
        self.placeholder_icon = "<:FeelsDeadMan:446396105077424138>"
        self.iconmap2 = {"Vale Guardian": "<:vale_guardian:449838205701718016>",
                        "Gorseval": "<:gorseval:449838206179868672>",
                        "Sabetha": "<:sabetha:449838205118971909>",
                        "Slothasor": "<:sloth:449838206045913098>",
                        "Matthias": "<:matthias:449838206054170645>",
                        "Keep Construct": "<:keep_construct:449838205731340290>",
                        "Xera": "<:xera:449838206100176896>",
                        "Cairn": "<:cairn:449838199523639307>",
                        "Mursaat Overseer": "<:mursaat_overseer:449838206310023168>",
                        "Samarog":"<:samarog:449838206205296650>",
                        "Deimos": "<:deimos:449838200295391232> ",
                        "Soulless Horror": "<:soulless_horror:449838201943621632>",
                        "Dhuum":"<:dhuum:449838200999903232>"}

        self.iconmap = {"Vale Guardian": "<:vale_guardian:451069804426559509>",
                        "Gorseval": "<:gorseval:451069805475135488>",
                        "Sabetha": "<:sabetha:451069805101973507>",
                        "Slothasor": "<:sloth:451069804720422913>",
                        "Matthias": "<:matthias:451069804993052682>",
                        "Keep Construct": "<:keep_construct:451069805475266570>",
                        "Xera": "<:xera:451069805060161536>",
                        "Cairn": "<:cairn:451069797116149761>",
                        "Mursaat Overseer": "<:mursaat_overseer:451069804800114689>",
                        "Samarog":"<:samarog:451069805764804608>",
                        "Deimos": "<:deimos:451069798093422613>",
                        "Soulless Horror": "<:soulless_horror:451069800123334675>",
                        "Dhuum":"<:dhuum:451069799355645982>"}

        self.hook_url = hook_url

        self.embed = Webhook(self.hook_url, color=0x483768)
        self.embed.set_desc("__***[Meta] Raid Run on "+self.date+"***__")
        self.embed.set_thumbnail("https://wiki.guildwars2.com/images/9/9d/Epidemic.png")
        self.embed.set_footer(text="Participants: Some people", ts=False)

    def set_bosses(self, bosses):
        """bosses is a dict that containts the bosses + links """
        self.bosses = bosses

    def add_bossfields(self):
        for key in self.bosses.keys():
            # make sure that this gets the abbreviated names !!
            self.embed.add_field(name=self.iconmap.get(key, self.placeholder_icon)+key, value="[dps.report]("+self.bosses[key]+" \""+self.bosses[key]+"\")")
            if self.iconmap.get(key, "whoops") == "Sabetha":
                self.embed.add_field(name="", value="")

    def post_to_discord(self):
        #self.embed.set_desc("I am a descriptive description describing in a descriptive way.")
        self.embed.set_author(name="Chrononono")
        self.embed.post()

    def test_message(self):
        test_message = self.embed
        test_message.add_field(name="This is a test!", value="Nothing to see here")
        test_message.set_desc("A very inconspicuous message")
        test_message.set_author(name="Rogue AI")
        test_message.set_footer(text="This is the last test, I promise!", ts=False)
        test_message.post()


# this is a thing that needs to bbe generated by the log uploader
#bosses = {"Vale Guardian": "https://dps.report/p0eu-20180521-220333_vg",
#           "Gorseval": "https://dps.report/Mios-20180521-220828_gorse",
#           "Sabetha": "https://dps.report/kZ1Y-20180525-192248_sab",
#           "Slothasor":"https://dps.report/RNrA-20180521-211924_sloth",
#           "Matthias": "https://dps.report/cDz1-20180525-193659_matt",
#           "Keep Construct": "https://dps.report/mfCd-20180521-205618_kc",
#           "Xera": "https://dps.report/RrK4-20180521-210827_xera",
#           "Cairn": "https://dps.report/8igT-20180521-190334_cairn",
#           "Mursaat Overseer": "https://dps.report/WARN-20180521-190741_mo",
#           "Samarog": "https://dps.report/oolK-20180521-192008_sam",
#           "Deimos": "https://dps.report/ls0E-20180521-194534_dei",
#           "Soulless Horror": "https://dps.report/E2PQ-20180521-195716_sh",
#           "Dhuum": "https://dps.report/gnqM-20180525-191100_dhuum"
#           }

#temp = cRaidclear()
#for key in bosses.keys():
#    embed.add_field(name=temp.iconmap.get(key, "whoops")+key, value="[dps.report]("+bosses[key]+" \""+bosses[key]+"\")")

#embed.set_thumbnail("https://wiki.guildwars2.com/images/9/9d/Epidemic.png")
#embed.set_footer(text="Participants: Some people", ts=False)

#embed.post()
