# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_gui.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(906, 908)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.frame_bosses = QtWidgets.QFrame(self.splitter)
        self.frame_bosses.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_bosses.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_bosses.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_bosses.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_bosses.setObjectName("frame_bosses")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_bosses)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gbWing1 = ButtonGroupBox(self.frame_bosses)
        self.gbWing1.setObjectName("gbWing1")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gbWing1)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.cbW1B1 = QtWidgets.QCheckBox(self.gbWing1)
        self.cbW1B1.setObjectName("cbW1B1")
        self.gridLayout_3.addWidget(self.cbW1B1, 1, 0, 1, 1)
        self.lW1B2 = QtWidgets.QLabel(self.gbWing1)
        self.lW1B2.setMinimumSize(QtCore.QSize(200, 0))
        self.lW1B2.setObjectName("lW1B2")
        self.gridLayout_3.addWidget(self.lW1B2, 2, 1, 1, 1)
        self.cbW1B2 = QtWidgets.QCheckBox(self.gbWing1)
        self.cbW1B2.setObjectName("cbW1B2")
        self.gridLayout_3.addWidget(self.cbW1B2, 2, 0, 1, 1)
        self.lW1B1 = QtWidgets.QLabel(self.gbWing1)
        self.lW1B1.setMinimumSize(QtCore.QSize(200, 0))
        self.lW1B1.setObjectName("lW1B1")
        self.gridLayout_3.addWidget(self.lW1B1, 1, 1, 1, 1)
        self.lW1B3 = QtWidgets.QLabel(self.gbWing1)
        self.lW1B3.setMinimumSize(QtCore.QSize(200, 0))
        self.lW1B3.setObjectName("lW1B3")
        self.gridLayout_3.addWidget(self.lW1B3, 3, 1, 1, 1)
        self.cbW1B3 = QtWidgets.QCheckBox(self.gbWing1)
        self.cbW1B3.setObjectName("cbW1B3")
        self.gridLayout_3.addWidget(self.cbW1B3, 3, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.gbWing1)
        self.gbWing2 = QtWidgets.QGroupBox(self.frame_bosses)
        self.gbWing2.setFlat(False)
        self.gbWing2.setCheckable(False)
        self.gbWing2.setObjectName("gbWing2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gbWing2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.cbW2B1_2 = QtWidgets.QCheckBox(self.gbWing2)
        self.cbW2B1_2.setObjectName("cbW2B1_2")
        self.gridLayout_2.addWidget(self.cbW2B1_2, 0, 0, 1, 1)
        self.lW2B1 = QtWidgets.QLabel(self.gbWing2)
        self.lW2B1.setMinimumSize(QtCore.QSize(200, 0))
        self.lW2B1.setObjectName("lW2B1")
        self.gridLayout_2.addWidget(self.lW2B1, 0, 1, 1, 1)
        self.cbW2B2_2 = QtWidgets.QCheckBox(self.gbWing2)
        self.cbW2B2_2.setObjectName("cbW2B2_2")
        self.gridLayout_2.addWidget(self.cbW2B2_2, 1, 0, 1, 1)
        self.lW2B2 = QtWidgets.QLabel(self.gbWing2)
        self.lW2B2.setMinimumSize(QtCore.QSize(200, 0))
        self.lW2B2.setObjectName("lW2B2")
        self.gridLayout_2.addWidget(self.lW2B2, 1, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.gbWing2)
        self.gbWing3 = QtWidgets.QGroupBox(self.frame_bosses)
        self.gbWing3.setFlat(False)
        self.gbWing3.setCheckable(False)
        self.gbWing3.setObjectName("gbWing3")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.gbWing3)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.cbW3B1 = QtWidgets.QCheckBox(self.gbWing3)
        self.cbW3B1.setObjectName("cbW3B1")
        self.gridLayout_5.addWidget(self.cbW3B1, 0, 0, 1, 1)
        self.lW3B1 = QtWidgets.QLabel(self.gbWing3)
        self.lW3B1.setMinimumSize(QtCore.QSize(200, 0))
        self.lW3B1.setObjectName("lW3B1")
        self.gridLayout_5.addWidget(self.lW3B1, 0, 1, 1, 1)
        self.cbW3B2 = QtWidgets.QCheckBox(self.gbWing3)
        self.cbW3B2.setObjectName("cbW3B2")
        self.gridLayout_5.addWidget(self.cbW3B2, 1, 0, 1, 1)
        self.lW3B2 = QtWidgets.QLabel(self.gbWing3)
        self.lW3B2.setMinimumSize(QtCore.QSize(200, 0))
        self.lW3B2.setObjectName("lW3B2")
        self.gridLayout_5.addWidget(self.lW3B2, 1, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.gbWing3)
        self.gbWing4 = QtWidgets.QGroupBox(self.frame_bosses)
        self.gbWing4.setFlat(False)
        self.gbWing4.setCheckable(False)
        self.gbWing4.setObjectName("gbWing4")
        self.gridLayout = QtWidgets.QGridLayout(self.gbWing4)
        self.gridLayout.setObjectName("gridLayout")
        self.cbW4B1 = QtWidgets.QCheckBox(self.gbWing4)
        self.cbW4B1.setObjectName("cbW4B1")
        self.gridLayout.addWidget(self.cbW4B1, 0, 0, 1, 1)
        self.lW4B1 = QtWidgets.QLabel(self.gbWing4)
        self.lW4B1.setMinimumSize(QtCore.QSize(200, 0))
        self.lW4B1.setObjectName("lW4B1")
        self.gridLayout.addWidget(self.lW4B1, 0, 1, 1, 1)
        self.cbW4B2 = QtWidgets.QCheckBox(self.gbWing4)
        self.cbW4B2.setObjectName("cbW4B2")
        self.gridLayout.addWidget(self.cbW4B2, 1, 0, 1, 1)
        self.lW4B2 = QtWidgets.QLabel(self.gbWing4)
        self.lW4B2.setMinimumSize(QtCore.QSize(200, 0))
        self.lW4B2.setObjectName("lW4B2")
        self.gridLayout.addWidget(self.lW4B2, 1, 1, 1, 1)
        self.cbW4B3 = QtWidgets.QCheckBox(self.gbWing4)
        self.cbW4B3.setObjectName("cbW4B3")
        self.gridLayout.addWidget(self.cbW4B3, 2, 0, 1, 1)
        self.lW4B3 = QtWidgets.QLabel(self.gbWing4)
        self.lW4B3.setMinimumSize(QtCore.QSize(200, 0))
        self.lW4B3.setObjectName("lW4B3")
        self.gridLayout.addWidget(self.lW4B3, 2, 1, 1, 1)
        self.cbW4B4 = QtWidgets.QCheckBox(self.gbWing4)
        self.cbW4B4.setObjectName("cbW4B4")
        self.gridLayout.addWidget(self.cbW4B4, 3, 0, 1, 1)
        self.lW4B4 = QtWidgets.QLabel(self.gbWing4)
        self.lW4B4.setMinimumSize(QtCore.QSize(200, 0))
        self.lW4B4.setObjectName("lW4B4")
        self.gridLayout.addWidget(self.lW4B4, 3, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.gbWing4)
        self.gbWing5 = QtWidgets.QGroupBox(self.frame_bosses)
        self.gbWing5.setFlat(False)
        self.gbWing5.setCheckable(False)
        self.gbWing5.setObjectName("gbWing5")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gbWing5)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.cbW5B1 = QtWidgets.QCheckBox(self.gbWing5)
        self.cbW5B1.setObjectName("cbW5B1")
        self.gridLayout_4.addWidget(self.cbW5B1, 0, 0, 1, 1)
        self.lW5B1 = QtWidgets.QLabel(self.gbWing5)
        self.lW5B1.setMinimumSize(QtCore.QSize(200, 0))
        self.lW5B1.setObjectName("lW5B1")
        self.gridLayout_4.addWidget(self.lW5B1, 0, 1, 1, 1)
        self.cbW5B2 = QtWidgets.QCheckBox(self.gbWing5)
        self.cbW5B2.setObjectName("cbW5B2")
        self.gridLayout_4.addWidget(self.cbW5B2, 1, 0, 1, 1)
        self.lW5B2 = QtWidgets.QLabel(self.gbWing5)
        self.lW5B2.setMinimumSize(QtCore.QSize(200, 0))
        self.lW5B2.setObjectName("lW5B2")
        self.gridLayout_4.addWidget(self.lW5B2, 1, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.gbWing5)
        self.gbFractals = QtWidgets.QGroupBox(self.frame_bosses)
        self.gbFractals.setFlat(False)
        self.gbFractals.setCheckable(False)
        self.gbFractals.setObjectName("gbFractals")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.gbFractals)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.cbFractal1B1 = QtWidgets.QCheckBox(self.gbFractals)
        self.cbFractal1B1.setObjectName("cbFractal1B1")
        self.gridLayout_6.addWidget(self.cbFractal1B1, 0, 0, 1, 1)
        self.lFractal1B1 = QtWidgets.QLabel(self.gbFractals)
        self.lFractal1B1.setMinimumSize(QtCore.QSize(200, 0))
        self.lFractal1B1.setObjectName("lFractal1B1")
        self.gridLayout_6.addWidget(self.lFractal1B1, 0, 1, 1, 1)
        self.cbFractal1B2 = QtWidgets.QCheckBox(self.gbFractals)
        self.cbFractal1B2.setObjectName("cbFractal1B2")
        self.gridLayout_6.addWidget(self.cbFractal1B2, 1, 0, 1, 1)
        self.lFractal1B2 = QtWidgets.QLabel(self.gbFractals)
        self.lFractal1B2.setMinimumSize(QtCore.QSize(200, 0))
        self.lFractal1B2.setObjectName("lFractal1B2")
        self.gridLayout_6.addWidget(self.lFractal1B2, 1, 1, 1, 1)
        self.cbFractal1B3 = QtWidgets.QCheckBox(self.gbFractals)
        self.cbFractal1B3.setObjectName("cbFractal1B3")
        self.gridLayout_6.addWidget(self.cbFractal1B3, 2, 0, 1, 1)
        self.lFractal1B3 = QtWidgets.QLabel(self.gbFractals)
        self.lFractal1B3.setMinimumSize(QtCore.QSize(200, 0))
        self.lFractal1B3.setObjectName("lFractal1B3")
        self.gridLayout_6.addWidget(self.lFractal1B3, 2, 1, 1, 1)
        self.cbFractal2B1 = QtWidgets.QCheckBox(self.gbFractals)
        self.cbFractal2B1.setObjectName("cbFractal2B1")
        self.gridLayout_6.addWidget(self.cbFractal2B1, 3, 0, 1, 1)
        self.lFractal2B1 = QtWidgets.QLabel(self.gbFractals)
        self.lFractal2B1.setMinimumSize(QtCore.QSize(200, 0))
        self.lFractal2B1.setObjectName("lFractal2B1")
        self.gridLayout_6.addWidget(self.lFractal2B1, 3, 1, 1, 1)
        self.cbFractal2B2 = QtWidgets.QCheckBox(self.gbFractals)
        self.cbFractal2B2.setObjectName("cbFractal2B2")
        self.gridLayout_6.addWidget(self.cbFractal2B2, 4, 0, 1, 1)
        self.lFractal2B2 = QtWidgets.QLabel(self.gbFractals)
        self.lFractal2B2.setMinimumSize(QtCore.QSize(200, 0))
        self.lFractal2B2.setObjectName("lFractal2B2")
        self.gridLayout_6.addWidget(self.lFractal2B2, 4, 1, 1, 1)
        self.cbFractal2B3 = QtWidgets.QCheckBox(self.gbFractals)
        self.cbFractal2B3.setObjectName("cbFractal2B3")
        self.gridLayout_6.addWidget(self.cbFractal2B3, 5, 0, 1, 1)
        self.lFractal2B3 = QtWidgets.QLabel(self.gbFractals)
        self.lFractal2B3.setMinimumSize(QtCore.QSize(200, 0))
        self.lFractal2B3.setObjectName("lFractal2B3")
        self.gridLayout_6.addWidget(self.lFractal2B3, 5, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.gbFractals)
        self.gbGolems = QtWidgets.QGroupBox(self.frame_bosses)
        self.gbGolems.setFlat(False)
        self.gbGolems.setCheckable(False)
        self.gbGolems.setObjectName("gbGolems")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.gbGolems)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.cbGolem1 = QtWidgets.QCheckBox(self.gbGolems)
        self.cbGolem1.setObjectName("cbGolem1")
        self.gridLayout_7.addWidget(self.cbGolem1, 0, 0, 1, 1)
        self.lW4B1_7 = QtWidgets.QLabel(self.gbGolems)
        self.lW4B1_7.setMinimumSize(QtCore.QSize(200, 0))
        self.lW4B1_7.setObjectName("lW4B1_7")
        self.gridLayout_7.addWidget(self.lW4B1_7, 0, 1, 1, 1)
        self.cbGolem2 = QtWidgets.QCheckBox(self.gbGolems)
        self.cbGolem2.setObjectName("cbGolem2")
        self.gridLayout_7.addWidget(self.cbGolem2, 1, 0, 1, 1)
        self.lW4B2_7 = QtWidgets.QLabel(self.gbGolems)
        self.lW4B2_7.setMinimumSize(QtCore.QSize(200, 0))
        self.lW4B2_7.setObjectName("lW4B2_7")
        self.gridLayout_7.addWidget(self.lW4B2_7, 1, 1, 1, 1)
        self.cbGolem3 = QtWidgets.QCheckBox(self.gbGolems)
        self.cbGolem3.setObjectName("cbGolem3")
        self.gridLayout_7.addWidget(self.cbGolem3, 2, 0, 1, 1)
        self.lW4B3_7 = QtWidgets.QLabel(self.gbGolems)
        self.lW4B3_7.setMinimumSize(QtCore.QSize(200, 0))
        self.lW4B3_7.setObjectName("lW4B3_7")
        self.gridLayout_7.addWidget(self.lW4B3_7, 2, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.gbGolems)
        self.fTemp = QtWidgets.QWidget(self.splitter)
        self.fTemp.setObjectName("fTemp")
        self.fOptions = QtWidgets.QFrame(self.splitter)
        self.fOptions.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fOptions.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fOptions.setObjectName("fOptions")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.fOptions)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton = QtWidgets.QPushButton(self.fOptions)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.gridLayout_8.addWidget(self.splitter, 1, 1, 1, 1)
        self.fFooter = QtWidgets.QFrame(self.centralwidget)
        self.fFooter.setMaximumSize(QtCore.QSize(16777215, 30))
        self.fFooter.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fFooter.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fFooter.setObjectName("fFooter")
        self.gridLayout_8.addWidget(self.fFooter, 2, 1, 1, 1)
        self.fHeader = QtWidgets.QWidget(self.centralwidget)
        self.fHeader.setMaximumSize(QtCore.QSize(16777215, 30))
        self.fHeader.setObjectName("fHeader")
        self.gridLayout_8.addWidget(self.fHeader, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 906, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.gbWing1.setTitle(_translate("MainWindow", "Spirit Vale"))
        self.cbW1B1.setText(_translate("MainWindow", "Vale Guardian"))
        self.lW1B2.setText(_translate("MainWindow", "TextLabel"))
        self.cbW1B2.setText(_translate("MainWindow", "Gorseval"))
        self.lW1B1.setText(_translate("MainWindow", "TextLabel"))
        self.lW1B3.setText(_translate("MainWindow", "TextLabel"))
        self.cbW1B3.setText(_translate("MainWindow", "Sabetha"))
        self.gbWing2.setTitle(_translate("MainWindow", "Salvation Pass"))
        self.cbW2B1_2.setText(_translate("MainWindow", "Slothasor"))
        self.lW2B1.setText(_translate("MainWindow", "TextLabel"))
        self.cbW2B2_2.setText(_translate("MainWindow", "Matthias"))
        self.lW2B2.setText(_translate("MainWindow", "TextLabel"))
        self.gbWing3.setTitle(_translate("MainWindow", "Stronghold of the Faithful"))
        self.cbW3B1.setText(_translate("MainWindow", "Keep Construct"))
        self.lW3B1.setText(_translate("MainWindow", "TextLabel"))
        self.cbW3B2.setText(_translate("MainWindow", "Xera"))
        self.lW3B2.setText(_translate("MainWindow", "TextLabel"))
        self.gbWing4.setTitle(_translate("MainWindow", "Bastion of the Penitent"))
        self.cbW4B1.setText(_translate("MainWindow", "Cairn"))
        self.lW4B1.setText(_translate("MainWindow", "TextLabel"))
        self.cbW4B2.setText(_translate("MainWindow", "Mursaat Overseer"))
        self.lW4B2.setText(_translate("MainWindow", "TextLabel"))
        self.cbW4B3.setText(_translate("MainWindow", "Samarog"))
        self.lW4B3.setText(_translate("MainWindow", "TextLabel"))
        self.cbW4B4.setText(_translate("MainWindow", "Deimos"))
        self.lW4B4.setText(_translate("MainWindow", "TextLabel"))
        self.gbWing5.setTitle(_translate("MainWindow", "Hall of Chains"))
        self.cbW5B1.setText(_translate("MainWindow", "Soulless Horror"))
        self.lW5B1.setText(_translate("MainWindow", "TextLabel"))
        self.cbW5B2.setText(_translate("MainWindow", "Dhuum"))
        self.lW5B2.setText(_translate("MainWindow", "TextLabel"))
        self.gbFractals.setTitle(_translate("MainWindow", "Fractals"))
        self.cbFractal1B1.setText(_translate("MainWindow", "MAMA"))
        self.lFractal1B1.setText(_translate("MainWindow", "TextLabel"))
        self.cbFractal1B2.setText(_translate("MainWindow", "Siax"))
        self.lFractal1B2.setText(_translate("MainWindow", "TextLabel"))
        self.cbFractal1B3.setText(_translate("MainWindow", "Ensolyss"))
        self.lFractal1B3.setText(_translate("MainWindow", "TextLabel"))
        self.cbFractal2B1.setText(_translate("MainWindow", "Skorvald"))
        self.lFractal2B1.setText(_translate("MainWindow", "TextLabel"))
        self.cbFractal2B2.setText(_translate("MainWindow", "Artsariiv"))
        self.lFractal2B2.setText(_translate("MainWindow", "TextLabel"))
        self.cbFractal2B3.setText(_translate("MainWindow", "Arkk"))
        self.lFractal2B3.setText(_translate("MainWindow", "TextLabel"))
        self.gbGolems.setTitle(_translate("MainWindow", "Golems"))
        self.cbGolem1.setText(_translate("MainWindow", "Standard Golem"))
        self.lW4B1_7.setText(_translate("MainWindow", "TextLabel"))
        self.cbGolem2.setText(_translate("MainWindow", "Medium Golem"))
        self.lW4B2_7.setText(_translate("MainWindow", "TextLabel"))
        self.cbGolem3.setText(_translate("MainWindow", "Large Golem"))
        self.lW4B3_7.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton.setText(_translate("MainWindow", "PushButton"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))

from gui.buttongroupbox import ButtonGroupBox
